#配置服务端口
server:
  port: 9898
#配置服务名
spring:
  #配置数据库连接参数
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bin_log_record?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root

  #时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  #redis配置
  redis:
    host: localhost
    port: 6379
    password:

#mybatis配置文件位置
mybatis:
  #指定xml文件存放路径
  mapper-locations: classpath:mapper/*.xml
  #驼峰命名转换
  configuration:
    map-underscore-to-camel-case: true

logging:
  #config: classpath:logback-spring.xml
  level:
    com.xmz.datarecordapplication: debug
    ROOT: INFO


auth:
  # authExcludePaths: /**
  useRedis: true
