#配置服务端口
server:
  port: 9898
#配置服务名
spring:
  #配置数据库连接参数
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bin_log_record?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root

  #时间格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


logging:
  #config: classpath:logback-spring.xml
  level:
    com.xmz.datarecordapplication: debug
    ROOT: INFO
